name: Test

on:
  push:
    # branches: [main]
    # paths-ignore:
    #   - 'README.md'
    #   - '.idea/**'
    #   - 'app/src/test/**'
    #   - 'app/src/androidTest/**'

jobs:
  test:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle Packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Setup Signing Store
        env:
          SIGNING_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}
        run: echo "$SIGNING_KEYSTORE" | openssl base64 -d -out key.jks
      - name: Set Version
        run: echo "VERSION=$(date '+%Y-%m-%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build APK
        env:
          VERSION_CODE: ${{ github.run_number }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: gradle assembleRelease --info
      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: "**/release/app-release.apk"
          if-no-files-found: error
          retention-days: 1
